### ISSUE TITLE
ustawić protection dla brancha: master

### ISSUE THREAD

**Issue by hamczu** [hihajdus/income-table#5]
+ jeden approval jest wymagany

**Comment by hihajdus** [comment]
zaznaczyłem --> Require pull request reviews before merging 
repozytorium musiałem ustawić jako publiczne

**Comment by hamczu** [comment]
aaa sorry, nie wiedziałem o tym - myślałem że można to zrobić w prywatnym repo w darmowym planie.
W takim razie może lepiej żeby było prywatne i po prostu się umawiamy że nie pushujemy do mastera?

**Comment by hamczu** [comment]
tak, po namyślę chyba wolałbym żeby nikt nie widział co tutaj robimy, szczególnie w godzinach pracy ;)
